<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<NpmBuild>true</NpmBuild>
		<Nullable>enable</Nullable>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<Target Name="NpmInstall" Inputs="package.json" Outputs="node_modules/.install-stamp">
		<Exec Command="npm install" />
		<Touch AlwaysCreate="true" Files="node_modules/.install-stamp" />
	</Target>
	<Target Name="NpmRunBuild" AfterTargets="AfterBuild" Condition="$(NpmBuild)" DependsOnTargets="NpmInstall">
		<Exec Command="npm run Build-$(Configuration)" />
	</Target>
</Project>